Repository Art-Diary/Frontend, pull requests merged in 2024-08, with the labels that each got.

#235 [refactor] 에디터에 사진 추가 시 스크롤되지 않는 것 해결
  android/app/src/main/AndroidManifest.xml
  src/api/auth.ts
  src/api/queries/auth.ts
  src/components/setting/EditPicture.tsx
  src/components/setting/UpdateProfile.tsx
  src/screens/login/LoginScreen.tsx
  src/screens/mydiary/chooseVisitDate/AddSoloVisitDateScreen.tsx
  src/screens/mydiary/writeDiary/CustomDiaryEditor.tsx
  src/screens/mydiary/writeDiary/GetPhoto.ts
  src/screens/mydiary/writeDiary/WriteMyDiaryInfoScreen.tsx
  src/screens/setting/LeaveScreen.tsx
Labels: refactor

#238 [237 feature] regexh파일 (새로운 전시회 등록 api)
  src/api/queries/regexh.ts
  src/api/regexh.ts
Labels: feature

#241 Feature/236 feature 전시회 등록 화면 구현
  src/App.tsx
  src/api/client.ts
  src/api/queries/regexh.ts
  src/api/regexh.ts
  src/assets/images/exh_plus.svg
  src/assets/images/index.ts
  src/components/common/icon.tsx
  src/screens/exhibition/ExhAddButton.tsx
  src/screens/exhibition/ExhAddFormScreen.tsx
  src/screens/exhibition/ExhListScreen.tsx
  src/utils/stackTypes.ts
Labels: feature

#243 [242 feature] 내가 등록한 전시회 목록 조회
  src/App.tsx
  src/screens/setting/PreviewRegExh.tsx
  src/screens/setting/RegisterNewExhScreen.tsx
  src/screens/setting/SettingScreen.tsx
  src/utils/stackTypes.ts
Labels: feature

#244 Feature/240 feature 전시회 일정 추가 구현
  src/components/common/CustomCalendar.tsx
  src/screens/exhibition/ExhAddFormScreen.tsx
  src/screens/exhibition/ExhSelectPeriodCalendar.tsx
  src/screens/exhibition/ExhSelectPeriodModal.tsx
  src/utils/date.ts
Labels: feature

#247 [refactor] 전시회 등록 폼 common 폴더로 분리
  src/api/queries/regexh.ts
  src/api/regexh.ts
  src/components/regexh/RegExhFormFrame.tsx
  src/screens/exhibition/ExhAddFormScreen.tsx
Labels: refactor

#250 [248 feature] ExhDetailInfo 공통부분 분리
  src/components/regexh/ExhDetailFormat.tsx
  src/components/regexh/ExhDetailHeart.tsx
  src/components/regexh/ExhDetailInfoIntro.tsx
  src/screens/exhibition/ExhDetailInfo.tsx
Labels: feature

#249 [feature] 등록 전시회 장소 추가 구현
  src/assets/images/exh_plus.svg
  src/components/common/icon.tsx
  src/components/regexh/ExhSelectPeriodCalendar.tsx
  src/components/regexh/ExhSelectPeriodModal.tsx
  src/components/regexh/RegExhFormFrame.tsx
  src/screens/exhibition/ExhAddButton.tsx
  src/utils/date.ts
Labels: feature

#251 [feature] 전시회 등록 완료 전의 미리보기 화면 구현
  src/components/regexh/RegExhFormFrame.tsx
  src/screens/exhibition/ExhAddFormScreen.tsx
  src/screens/exhibition/RegExhPreviewModal.tsx
Labels: feature, refactor

#254 전시회 등록 현황 확인 페이지 구현
  src/App.tsx
  src/api/queries/regexh.ts
  src/api/regexh.ts
  src/components/regexh/ExhDetailFormat.tsx
  src/screens/setting/CheckRegExh.tsx
  src/screens/setting/PreviewRegExh.tsx
  src/screens/setting/RegisterNewExhScreen.tsx
  src/utils/stackTypes.ts
Labels: feature
