Repository Art-Diary/Frontend, pull requests merged in 2024-07, with the labels that each got.

#174 [feature] 뒤로 버튼 두 번 클릭 시 앱 종료
  src/routes/BottomRoutes.tsx
Labels: feature

#176 [175 feature] 홈페이지로 이동
  src/screens/exhibition/ExhDetailInfo.tsx
Labels: feature

#177 [refactor] 설정 화면 반응형 디자인 적용
  package.json
  src/assets/images/profile_update_icon.svg
  src/assets/name_tag/grey_tag.svg
  src/assets/name_tag/login_tag.svg
  src/assets/name_tag/profile_tag.svg
  src/components/common/GreyNameTag.tsx
  src/components/common/Header.tsx
  src/components/common/ResponsiveSize.tsx
  src/components/common/colors.ts
  src/components/common/modal/toastConfig.tsx
  src/components/common/style.ts
  src/routes/BottomRoutes.tsx
  src/screens/login/LoginScreen.tsx
  src/screens/setting/SettingScreen.tsx
  src/screens/setting/nameTag/ProfileNameTag.tsx
Labels: refactor

#183 Refactor/181 refactor 설정 탭 화면 반응형 디자인 적용
  src/assets/images/back_button.svg
  src/assets/images/empty_heart.svg
  src/assets/images/full_heart.svg
  src/assets/images/index.ts
  src/assets/images/private_toggle.svg
  src/assets/images/public_toggle.svg
  src/components/common/BackView.tsx
  src/components/common/ErrorMessageView.tsx
  src/components/common/GreyNameTag.tsx
  src/components/common/Header.tsx
  src/components/common/ResponsiveSize.tsx
  src/components/common/colors.ts
  src/components/common/icon.tsx
  src/components/common/modal/toastConfig.tsx
  src/components/common/style.ts
  src/components/diary/OtherInfo.tsx
  src/components/exhibition/ExhItemView.tsx
  src/components/setting/EditArtCategory.tsx
  src/components/setting/EditNickname.tsx
  src/components/setting/EditPicture.tsx
  src/components/setting/UpdateProfile.tsx
  src/routes/BottomRoutes.tsx
  src/routes/setting/SettingRoutes.tsx
  src/screens/exhibition/ExhDetailInfo.tsx
  src/screens/exhibition/ExhListScreen.tsx
  src/screens/login/LoginScreen.tsx
  src/screens/setting/EditProfileScreen.tsx
  src/screens/setting/LeaveScreen.tsx
  src/screens/setting/SettingScreen.tsx
  src/screens/setting/favoriteList/EditFavoriteScreen.tsx
  src/screens/setting/favoriteList/FavoriteListScreen.tsx
  src/screens/setting/favoriteList/FetchFavoriteList.tsx
  src/screens/setting/nameTag/ProfileNameTag.tsx
  src/screens/setting/updateAlarm/AlarmSettingScreen.tsx
  src/screens/setting/updateAlarm/UpdateAlarm1.tsx
  src/screens/setting/updateAlarm/UpdateAlarm2.tsx
  src/screens/setting/updateAlarm/UpdateAlarm3.tsx
Labels: refactor

#184 [refactor] 내 기록 탭 화면 반응형 디자인 적용
  src/assets/images/add_my_exh_button.svg
  src/assets/images/avg_rate_star.svg
  src/assets/images/empty_star.svg
  src/assets/images/empty_star_icon.svg
  src/assets/images/full_star.svg
  src/assets/images/index.ts
  src/assets/images/option_bar.svg
  src/assets/images/write_diary_button.svg
  src/assets/images/writer_icon.svg
  src/assets/images/writer_pencil.svg
  src/components/common/CustomCalendar.tsx
  src/components/common/ResponsiveSize.tsx
  src/components/common/icon.tsx
  src/components/common/modal/ConfirmationModal.tsx
  src/components/common/modal/LoadingModal.tsx
  src/components/common/modal/toastConfig.tsx
  src/components/common/style.ts
  src/components/diary/AddVisitDate.tsx
  src/components/diary/ContentsInfo.tsx
  src/components/diary/DiaryBackFrame.tsx
  src/components/diary/DiaryList.tsx
  src/components/diary/OtherInfo.tsx
  src/components/diary/SayingInfo.tsx
  src/components/diary/ThumbnailInfo.tsx
  src/components/diary/TitleInfo.tsx
  src/components/diary/UpdateDelete.tsx
  src/components/diary/VisitedExhListFrame.tsx
  src/components/diary/WriterRateInfo.tsx
  src/components/diary/modal/DeleteDiaryModal.tsx
  src/components/exhSearch/SearchExhFrame.tsx
  src/components/exhSearch/SearchExhResult.tsx
  src/screens/calendar/ExhListOfDayInCalendar.tsx
  src/screens/calendar/calendarDiary/CalendarDiaryList.tsx
  src/screens/calendar/calendarDiary/CalendarDiaryListScreen.tsx
  src/screens/exhibition/ExhDetailInfo.tsx
  src/screens/exhibition/ExhToCal.tsx
  src/screens/exhibition/ExhToDiary.tsx
  src/screens/mate/gathering/FetchGatheringDiaryList.tsx
  src/screens/mate/gathering/GatheringDiaryListScreen.tsx
  src/screens/mate/gathering/GatheringInfoScreen.tsx
  src/screens/mate/gathering/addVisitExhibition/NewVisitDateInGathering.tsx
  src/screens/mate/main/MateMainScreen.tsx
  src/screens/mydiary/MyExhList.tsx
  src/screens/mydiary/MyExhListScreen.tsx
  src/screens/mydiary/MyExhSearchScreen.tsx
  src/screens/mydiary/chooseVisitDate/AddSoloVisitDateScreen.tsx
  src/screens/mydiary/chooseVisitDate/ChooseVisitDateList.tsx
  src/screens/mydiary/chooseVisitDate/ChooseVisitDateScreen.tsx
  src/screens/mydiary/mydiaryList/MyDiaryList.tsx
  src/screens/mydiary/mydiaryList/MyDiaryListScreen.tsx
  src/screens/mydiary/writeDiary/CustomDiaryEditor.tsx
  src/screens/mydiary/writeDiary/WriteMyDiaryContentsScreen.tsx
  src/screens/mydiary/writeDiary/WriteMyDiaryInfoScreen.tsx
Labels: refactor

#186 [bug] 기록 삭제 반영 안되는 문제 해결
  src/api/queries/mydiary.ts
  src/components/diary/modal/DeleteDiaryModal.tsx
Labels: bug

#188 Refactor/187 refactor 전시메이트 탭과 캘린더 탭 화면 반응형 디자인 적용
  src/api/queries/exhibition.ts
  src/api/queries/mate.ts
  src/api/queries/mydiary.ts
  src/assets/images/index.ts
  src/assets/images/leave_gathering.svg
  src/assets/images/search_button.svg
  src/assets/name_tag/pink_tag.svg
  src/components/common/CustomCalendar.tsx
  src/components/common/icon.tsx
  src/components/diary/TitleInfo.tsx
  src/components/exhSearch/SearchExhFrame.tsx
  src/components/exhibition/ExhItemView.tsx
  src/components/mate/NameList.tsx
  src/screens/calendar/CalendarScreen.tsx
  src/screens/calendar/ExhListOfDayInCalendar.tsx
  src/screens/calendar/GatheringSelector.tsx
  src/screens/exhibition/ExhSearchName.tsx
  src/screens/mate/NameTag.tsx
  src/screens/mate/gathering/AddNewMateInGatheringScreen.tsx
  src/screens/mate/gathering/GatheringInfoScreen.tsx
  src/screens/mate/gathering/SearchNewMateListInGathering.tsx
  src/screens/mate/gathering/addVisitExhibition/NewVisitDateOfExhInGatheringScreen.tsx
  src/screens/mate/gathering/addVisitExhibition/SearchAddVisitExhInGatheringScreen.tsx
  src/screens/mate/main/AddNewMateScreen.tsx
  src/screens/mate/main/CreateGatheringScreen.tsx
  src/screens/mate/main/ExhMateList.tsx
  src/screens/mate/main/MateMainScreen.tsx
  src/screens/mate/main/SearchNewMateList.tsx
  src/screens/mate/mate/mateExhList/MateExhListScreen.tsx
  src/screens/mydiary/MyExhSearchScreen.tsx
Labels: refactor

#195 [refactor] 동일한 이메일을 가진 소셜 로그인 통합 관련 모달 구현
  src/api/auth.ts
  src/api/queries/auth.ts
  src/screens/login/EmailDuplicateModal.tsx
  src/screens/login/LoginScreen.tsx
Labels: refactor

#199 [bug] 전시회 상세 페이지 리뷰 수정 바로 반영되도록 수정
  src/api/queries/mydiary.ts
  src/components/diary/DiaryList.tsx
  src/screens/calendar/calendarDiary/CalendarDiaryList.tsx
  src/screens/calendar/calendarDiary/CalendarDiaryListScreen.tsx
  src/screens/exhibition/ExhToDiary.tsx
  src/screens/exhibition/ExhToMoreReview.tsx
  src/screens/mate/gathering/FetchGatheringDiaryList.tsx
  src/screens/mate/gathering/GatheringDiaryListScreen.tsx
  src/screens/mydiary/mydiaryList/MyDiaryListScreen.tsx
  src/screens/mydiary/writeDiary/WriteMyDiaryContentsScreen.tsx
Labels: bug, refactor

#201 [bug] 전시회 상세 페이지 리뷰 삭제 바로 반영되도록 수정
  src/api/queries/mydiary.ts
  src/components/diary/modal/DeleteDiaryModal.tsx
  src/screens/exhibition/ExhToMoreReview.tsx
Labels: bug

#202 [198 feature] 검색 기록 조회
  src/api/exhibition.ts
  src/api/queries/exhibition.ts
  src/screens/exhibition/ExhSearchName.tsx
Labels: feature

#204 [refactor] 폴더 이름 변경
  src/routes/mydiary/AddMyVisitDateRoutes.tsx
  src/routes/mydiary/MyDiaryRoutes.tsx
  src/routes/mydiary/WriteMyDiaryRoutes.tsx
  src/screens/mydiary/myDiaryList/MyDiaryBackScreen.tsx
  src/screens/mydiary/myDiaryList/MyDiaryListScreen.tsx
Labels: refactor

#206 [refactor] 내 기록과 캘린더 관련 api 중 새로운 전시방문 및 기록 엔티티가 적용된 반환 값으로 수정
  src/App.tsx
  src/api/mydiary.ts
  src/api/queries/mydiary.ts
  src/components/diary/DiaryList.tsx
  src/components/diary/OtherInfo.tsx
  src/components/diary/modal/DeleteDiaryModal.tsx
  src/screens/calendar/ExhListOfDayInCalendar.tsx
  src/screens/calendar/calendarDiary/CalendarDiaryListScreen.tsx
  src/screens/exhibition/ExhToCal.tsx
  src/screens/mydiary/chooseVisitDate/AddSoloVisitDateScreen.tsx
  src/screens/mydiary/chooseVisitDate/ChooseVisitDateList.tsx
  src/screens/mydiary/chooseVisitDate/ChooseVisitDateScreen.tsx
  src/screens/mydiary/chooseVisitDate/FetchMyStoredDateListOfExh.tsx
  src/screens/mydiary/writeDiary/WriteMyDiaryContentsScreen.tsx
  src/screens/mydiary/writeDiary/WriteMyDiaryInfoScreen.tsx
  src/utils/dataTypes.ts
  src/utils/stackTypes.ts
  src/zustand/calendar/exhFromCalendar.ts
  src/zustand/mydiary/mySoloMarkedDates.ts
  src/zustand/mydiary/mydiary.ts
  src/zustand/mydiary/writeMyDiary.ts
Labels: refactor

#209 [feature] 요청 헤더에 jwt 추가
  src/App.tsx
  src/api/auth.ts
  src/api/client.ts
  src/api/navigationService.ts
  src/api/queries/auth.ts
  src/api/queries/exhibition.ts
  src/routes/mate/GatheringRoutes.tsx
  src/routes/setting/SettingRoutes.tsx
  src/screens/login/LoginScreen.tsx
  src/screens/setting/SettingScreen.tsx
Labels: feature

#212 [refactor] 점을 포함한 형식의 날짜 반환 데이터 반영
  src/components/common/CustomCalendar.tsx
  src/components/diary/AddVisitDate.tsx
  src/components/diary/DiaryBackFrame.tsx
  src/components/diary/OtherInfo.tsx
  src/components/exhibition/ExhItemView.tsx
  src/screens/calendar/CalendarScreen.tsx
  src/screens/calendar/ExhListOfDayInCalendar.tsx
  src/screens/exhibition/ExhDetailInfo.tsx
  src/screens/exhibition/ExhSearchByDate.tsx
  src/screens/exhibition/ExhToCal.tsx
  src/screens/exhibition/ExhToMoreReview.tsx
  src/screens/mate/gathering/addVisitExhibition/NewVisitDateInGathering.tsx
  src/screens/mydiary/chooseVisitDate/ChooseVisitDateList.tsx
  src/utils/Date.ts
  src/utils/dataTypes.ts
  src/utils/deeplinkConfig.ts
  src/zustand/calendar/dateFromExh.ts
  src/zustand/mydiary/mySoloMarkedDates.ts
Labels: refactor

#213 [refactor] 모임 셀렉터 너비 변경 및 한마디 입력 칸 밀림 현상 해결
  src/components/diary/SayingInfo.tsx
  src/screens/calendar/GatheringSelector.tsx
  src/screens/calendar/calendarColor.ts
  src/screens/mate/main/GatheringListRequest.tsx
  src/screens/mydiary/writeDiary/WriteMyDiaryContentsScreen.tsx
  src/screens/mydiary/writeDiary/WriteMyDiaryInfoScreen.tsx
Labels: refactor

#215 Refactor/214 refactor base64 형식 사진 데이터에서 s3 사진 url로 변경으로 인한 수정
  env.d.ts
  src/api/mydiary.ts
  src/api/queries/auth.ts
  src/api/queries/mydiary.ts
  src/components/diary/DiaryList.tsx
  src/components/diary/ThumbnailInfo.tsx
  src/components/diary/VisitedExhListFrame.tsx
  src/components/exhSearch/SearchExhResult.tsx
  src/components/exhibition/ExhItemView.tsx
  src/components/setting/EditPicture.tsx
  src/components/setting/UpdateProfile.tsx
  src/screens/calendar/calendarDiary/CalendarDiaryListScreen.tsx
  src/screens/exhibition/ExhDetailInfo.tsx
  src/screens/exhibition/ExhToMoreReview.tsx
  src/screens/exhibition/Link.ts
  src/screens/mate/gathering/GatheringDiaryListScreen.tsx
  src/screens/mate/gathering/SearchNewMateListInGathering.tsx
  src/screens/mate/main/ExhMateList.tsx
  src/screens/mate/main/SearchNewMateList.tsx
  src/screens/mate/mate/mateExhList/MateExhListScreen.tsx
  src/screens/mydiary/chooseVisitDate/FetchMyStoredDateListOfExh.tsx
  src/screens/mydiary/myDiaryList/MyDiaryListScreen.tsx
  src/screens/mydiary/writeDiary/WriteMyDiaryContentsScreen.tsx
  src/screens/mydiary/writeDiary/WriteMyDiaryInfoScreen.tsx
  src/screens/setting/nameTag/ProfileNameTag.tsx
  src/utils/resizeImage.ts
  src/zustand/mydiary/writeMyDiary.ts
  src/zustand/tabIdentifier.ts
Labels: refactor

#219 Refactor/216 refactor 기록 내용 중 첨부 사진 데이터 추가
  src/components/diary/ContentsInfo.tsx
  src/screens/exhibition/ExhDetailInfo.tsx
  src/screens/mate/mate/mateExhList/MateExhListScreen.tsx
  src/screens/mydiary/chooseVisitDate/ChooseVisitDateList.tsx
  src/screens/mydiary/writeDiary/CustomDiaryEditor.tsx
  src/screens/mydiary/writeDiary/GetPhoto.ts
  src/screens/mydiary/writeDiary/WriteMyDiaryContentsScreen.tsx
  src/screens/setting/nameTag/ProfileNameTag.tsx
Labels: refactor

#222 Feature/217 feature 페이지 새로고침 추가 및 커스텀 touchable로 교체
  android/app/src/main/AndroidManifest.xml
  src/App.tsx
  src/components/common/BackView.tsx
  src/components/common/CustomCalendar.tsx
  src/components/common/CustomTouchable.tsx
  src/components/common/GreyNameTag.tsx
  src/components/diary/AddVisitDate.tsx
  src/components/diary/VisitedExhListFrame.tsx
  src/components/diary/modal/DeleteDiaryModal.tsx
  src/components/exhSearch/SearchExhFrame.tsx
  src/components/exhibition/ExhItemView.tsx
  src/components/exhibition/OptionsModal.tsx
  src/components/mate/NameList.tsx
  src/components/setting/EditNickname.tsx
  src/components/setting/EditPicture.tsx
  src/components/setting/UpdateProfile.tsx
  src/screens/calendar/CalendarScreen.tsx
  src/screens/calendar/ExhListOfDayInCalendar.tsx
  src/screens/calendar/GatheringSelector.tsx
  src/screens/calendar/calendarDiary/CalendarDiaryListScreen.tsx
  src/screens/exhibition/ExhDetailInfo.tsx
  src/screens/exhibition/ExhListScreen.tsx
  src/screens/exhibition/ExhSearchByDate.tsx
  src/screens/exhibition/ExhSearchModal.tsx
  src/screens/exhibition/ExhSearchName.tsx
  src/screens/exhibition/ExhShare.tsx
  src/screens/exhibition/ExhShareModal.tsx
  src/screens/exhibition/ExhToDiary.tsx
  src/screens/exhibition/ExhToMoreReview.tsx
  src/screens/login/EmailDuplicateModal.tsx
  src/screens/login/LoginScreen.tsx
  src/screens/mate/gathering/AddNewMateInGatheringScreen.tsx
  src/screens/mate/gathering/GatheringDiaryListScreen.tsx
  src/screens/mate/gathering/GatheringInfoScreen.tsx
  src/screens/mate/gathering/SearchNewMateListInGathering.tsx
  src/screens/mate/main/AddNewMateScreen.tsx
  src/screens/mate/main/CreateGatheringScreen.tsx
  src/screens/mate/main/ExhMateList.tsx
  src/screens/mate/main/GatheringListRequest.tsx
  src/screens/mate/main/MateMainScreen.tsx
  src/screens/mate/main/SearchNewMateList.tsx
  src/screens/mate/mate/mateExhList/MateExhList.tsx
  src/screens/mydiary/MyExhListScreen.tsx
  src/screens/mydiary/chooseVisitDate/AddSoloVisitDateScreen.tsx
  src/screens/mydiary/chooseVisitDate/ChooseVisitDateList.tsx
  src/screens/mydiary/myDiaryList/MyDiaryListScreen.tsx
  src/screens/mydiary/writeDiary/CustomDiaryEditor.tsx
  src/screens/mydiary/writeDiary/WriteMyDiaryContentsScreen.tsx
  src/screens/mydiary/writeDiary/WriteMyDiaryInfoScreen.tsx
  src/screens/setting/LeaveScreen.tsx
  src/screens/setting/favoriteList/EditFavoriteScreen.tsx
  src/screens/setting/favoriteList/FavoriteListScreen.tsx
  src/screens/setting/nameTag/ProfileNameTag.tsx
  src/screens/setting/updateAlarm/UpdateAlarm1.tsx
  src/screens/setting/updateAlarm/UpdateAlarm2.tsx
  src/screens/setting/updateAlarm/UpdateAlarm3.tsx
Labels: feature, refactor

#223 Refactor/220 refactor 앨범 접근 권한 요청과 알림 허용 권한 요청 수정 및 푸시 알림 수정
  android/app/src/main/AndroidManifest.xml
  index.ts
  package.json
  src/App.tsx
  src/components/common/CustomCalendar.tsx
  src/components/diary/AddVisitDate.tsx
  src/components/diary/SayingInfo.tsx
  src/components/exhSearch/SearchExhResult.tsx
  src/components/exhibition/ExhItemView.tsx
  src/components/setting/EditNickname.tsx
  src/components/setting/EditPicture.tsx
  src/screens/calendar/CalendarScreen.tsx
  src/screens/calendar/ExhListOfDayInCalendar.tsx
  src/screens/calendar/calendarDiary/CalendarDiaryListScreen.tsx
  src/screens/exhibition/ExhDetailInfo.tsx
  src/screens/exhibition/ExhSearchByDate.tsx
  src/screens/exhibition/ExhSearchName.tsx
  src/screens/exhibition/ExhToCal.tsx
  src/screens/login/LoginScreen.tsx
  src/screens/login/UserInfo.tsx
  src/screens/mate/gathering/AddNewMateInGatheringScreen.tsx
  src/screens/mate/gathering/GatheringDiaryListScreen.tsx
  src/screens/mate/gathering/addVisitExhibition/NewVisitDateInGathering.tsx
  src/screens/mate/gathering/addVisitExhibition/SearchAddVisitExhInGatheringScreen.tsx
  src/screens/mate/main/AddNewMateScreen.tsx
  src/screens/mate/main/CreateGatheringScreen.tsx
  src/screens/mydiary/MyExhSearchScreen.tsx
  src/screens/mydiary/chooseVisitDate/AddSoloVisitDateScreen.tsx
  src/screens/mydiary/chooseVisitDate/ChooseVisitDateList.tsx
  src/screens/mydiary/myDiaryList/MyDiaryListScreen.tsx
  src/screens/mydiary/writeDiary/GetPhoto.ts
  src/screens/mydiary/writeDiary/WriteMyDiaryContentsScreen.tsx
  src/screens/mydiary/writeDiary/WriteMyDiaryInfoScreen.tsx
  src/screens/setting/SettingScreen.tsx
  src/screens/setting/nameTag/ProfileNameTag.tsx
  src/utils/keyword.ts
  src/utils/photo.ts
  src/zustand/calendar/addSchedule.ts
Labels: refactor

#225 Refactor/221 refactor 글자 수 제한 예시
  android/app/src/main/AndroidManifest.xml
  index.js
  src/components/diary/OtherInfo.tsx
  src/components/diary/WriterRateInfo.tsx
  src/components/setting/EditNickname.tsx
  src/screens/mate/main/CreateGatheringScreen.tsx
  src/screens/mydiary/writeDiary/WriteMyDiaryContentsScreen.tsx
  src/screens/mydiary/writeDiary/WriteMyDiaryInfoScreen.tsx
  src/screens/setting/LeaveScreen.tsx
  src/utils/date.ts
Labels: refactor

#227 [refactor] 전시회 상세 코드 분리 및 소개 html 렌더링 사용
  src/api/queries/exhibition.ts
  src/components/exhibition/ExhItemView.tsx
  src/screens/calendar/GatheringSelector.tsx
  src/screens/exhibition/ExhDetailInfo.tsx
  src/screens/exhibition/ExhListScreen.tsx
  src/screens/exhibition/detail/ExhDetailHeart.tsx
  src/screens/exhibition/detail/ExhDetailInfoIntro.tsx
  src/screens/exhibition/detail/ExhReviewList.tsx
  src/screens/setting/favoriteList/EditFavoriteScreen.tsx
  src/zustand/setting/favoriteList.ts
Labels: refactor

#229 [228 Refactor] NewVisitDateInGathering 수정
  src/screens/mate/gathering/addVisitExhibition/NewVisitDateInGathering.tsx
Labels: refactor

#231 [refactor] 전시회 상세 페이지 아이콘 이동
  src/screens/exhibition/ExhDetailInfo.tsx
  src/screens/exhibition/detail/ExhDetailHeart.tsx
  src/screens/exhibition/detail/ExhDetailInfoIntro.tsx
Labels: refactor

#233 [refactor] 캘린더 전시회 모임 위치 변경
  src/components/exhibition/ExhItemView.tsx
  src/screens/calendar/ExhListOfDayInCalendar.tsx
Labels: refactor
