Repository Art-Diary/Frontend, pull requests merged in 2024-12, with the labels that each got.

#280 [refactor] 전시회 상세 페이지를 통한 방문 날짜 추가 모달 수정
  src/api/mydiary.ts
  src/api/queries/mydiary.ts
  src/components/regexh/ExhDetailFormat.tsx
  src/screens/exhibition/ExhToCal.tsx
  src/screens/mydiary/chooseVisitDate/AddSoloVisitDateScreen.tsx
Labels: refactor

#282 [bug] 전시회 상세 페이지의 좋아요 하트 연속 안 눌림 오류 해결
  src/api/queries/exhibition.ts
  src/components/regexh/ExhDetailHeart.tsx
  src/screens/exhibition/ExhListScreen.tsx
  src/screens/setting/favoriteList/EditFavoriteScreen.tsx
Labels: bug

#283 [feature] 관리자용 전시회 상세정보 수정 화면 추가
  src/App.tsx
  src/api/exhibition.ts
  src/api/queries/exhibition.ts
  src/assets/images/edit_reg_exh.svg
  src/assets/images/trash_reg_exh.svg
  src/components/common/icon.tsx
  src/components/exhibition/ExhDetailFormat.tsx
  src/components/exhibition/ExhDetailHeart.tsx
  src/components/exhibition/ExhDetailInfoIntro.tsx
  src/components/exhibition/ExhFormFrame.tsx
  src/components/exhibition/ExhSelectPeriodCalendar.tsx
  src/components/exhibition/ExhSelectPeriodModal.tsx
  src/components/exhibition/RegExhOptionsModal.tsx
  src/screens/exhibition/ExhAddFormScreen.tsx
  src/screens/exhibition/ExhDetailEditScreen.tsx
  src/screens/exhibition/ExhDetailInfo.tsx
  src/screens/exhibition/RegExhPreviewModal.tsx
  src/screens/setting/CheckRegExh.tsx
  src/screens/setting/ConfirmRegExh.tsx
  src/screens/setting/ConfirmRegExhScreen.tsx
  src/screens/setting/EditRegExhByUser.tsx
  src/screens/setting/ShowConfirmedRegExh.tsx
  src/utils/dataTypes.ts
  src/utils/stackTypes.ts
Labels: feature

#286 Refactor/285 refactor 기록 작성 폼 디자인 수정
  src/components/common/ImageInputForm.tsx
  src/components/common/TextInputForm.tsx
  src/components/common/colors.ts
  src/components/common/diary/PublicSelector.tsx
  src/components/common/diary/SayingInputForm.tsx
  src/components/common/diary/StarRateSelector.tsx
  src/components/gathering/SelectNewVisitDateForGathering.tsx
  src/screens/mydiary/writeDiary/CustomDiaryEditor.tsx
  src/screens/mydiary/writeDiary/GetPhoto.ts
  src/screens/mydiary/writeDiary/WriteMyDiaryContentsScreen.tsx
  src/screens/mydiary/writeDiary/WriteMyDiaryInfoScreen.tsx
  src/types/index.ts
Labels: refactor

#292 [refactor] 캘린더 디자인 변경
  src/components/calendar/CalendarGatheringSelector.tsx
  src/components/calendar/ExhListOfDayInCalendar.tsx
  src/components/calendar/GatheringSelector.tsx
  src/components/calendar/calendarColor.ts
  src/components/common/CalendarFrame.tsx
  src/components/common/diary/VisitedDateListForDiary.tsx
  src/components/common/modal/InfoModal.tsx
  src/components/exhibition/ExhItemView.tsx
  src/components/gathering/SelectNewVisitDateForGathering.tsx
  src/screens/calendar/CalendarScreen.tsx
  src/screens/calendar/GatheringSelector.tsx
  src/screens/calendar/calendarColor.ts
  src/screens/exhibition/ExhToCal.tsx
  src/types/index.ts
Labels: refactor

#276 [275 feature]검색어로 전시회검색결과 조회 수정
  src/api/exhibition.ts
  src/api/queries/exhibition.ts
  src/assets/images/delete_button.svg
  src/assets/images/index.ts
  src/components/common/icon.tsx
  src/components/exhSearch/SearchExhFrame.tsx
  src/screens/exhibition/ExhListBySearchContentsScreen.tsx
  src/screens/exhibition/ExhSearchName.tsx
  src/screens/exhibition/SearchContentsListScreen.tsx
Labels: feature

#293 [refactor] 캘린더의 특정 날짜에 전시회 추가 로직 변경
  src/api/queries/calendar.ts
  src/api/queries/mydiary.ts
  src/assets/images/index.ts
  src/assets/images/info_button.svg
  src/components/calendar/ExhListOfDayInCalendar.tsx
  src/components/calendar/modal/AddVisitExhToCalModal.tsx
  src/components/common/diary/modal/SearchExhForDiaryModal.tsx
  src/components/common/exhibition/SearchExhResult.tsx
  src/components/common/icon.tsx
  src/components/common/modal/InfoModal.tsx
  src/components/exhibition/ExhDetailFormat.tsx
  src/components/exhibition/ExhDetailInfoIntro.tsx
  src/components/mydiary/modal/AddVisitedDateForDiaryModal.tsx
  src/routes/BottomRoutes.tsx
  src/screens/calendar/CalendarScreen.tsx
  src/screens/exhibition/ExhDetailEditScreen.tsx
  src/screens/exhibition/ExhDetailInfo.tsx
  src/screens/exhibition/ExhToCal.tsx
  src/types/index.ts
  src/utils/dataTypes.ts
  src/utils/stackTypes.ts
Labels: refactor

#294 [refactor] 기록 수정과 삭제 모달 디자인 변경
  src/assets/images/close_button.svg
  src/assets/images/index.ts
  src/assets/images/pencil_update.svg
  src/assets/images/trash_delete.svg
  src/components/common/diary/DiaryList.tsx
  src/components/common/diary/VisitedDateListForDiary.tsx
  src/components/common/diary/modal/DeleteDiaryModal.tsx
  src/components/common/diary/modal/DiaryUpdateDeleteModal.tsx
  src/components/common/icon.tsx
  src/components/common/modal/DecisionModal.tsx
  src/components/common/style.ts
  src/components/gathering/FetchGatheringDiaryList.tsx
  src/screens/calendar/calendarDiary/CalendarDiaryListScreen.tsx
  src/screens/exhibition/ExhToDiary.tsx
  src/screens/mate/gathering/GatheringDiaryListScreen.tsx
  src/screens/mate/mate/mateDiary/FetchMateDiaryList.tsx
  src/screens/mydiary/MyDiaryListScreen.tsx
Labels: refactor

#298 [bug] 기록 수정 시 모임에서 개인 방문 날짜로 변경 시 기존에 선택한 날짜 선택 해제 불가 오류 해결
  src/components/common/CalendarFrame.tsx
  src/components/common/diary/VisitedDateListForDiary.tsx
  src/screens/calendar/CalendarScreen.tsx
  src/screens/mydiary/CreateExhVisitedDateScreen.tsx
Labels: bug

#300 [295 refactor] 검색어로 전시회 조회 모달 수정
  src/components/exhSearch/SearchExhFrame.tsx
  src/screens/exhibition/ExhListBySearchContentsScreen.tsx
  src/screens/exhibition/ExhSearchName.tsx
  src/screens/exhibition/SearchContentsListScreen.tsx
Labels: refactor

#303 [refactor] 모임 메이트 추가 페이지를 모달로 변경
  src/api/queries/exhibition.ts
  src/api/queries/gathering.ts
  src/components/common/diary/modal/SearchExhForDiaryModal.tsx
  src/components/exhSearch/SearchExhFrame.tsx
  src/components/gathering/AddNewMateInGatheringModal.tsx
  src/components/gathering/SearchNewMateListInGathering.tsx
  src/components/mate/AddNewMateModal.tsx
  src/routes/mate/GatheringRoutes.tsx
  src/screens/mate/gathering/GatheringInfoScreen.tsx
  src/screens/mate/gathering/SearchNewMateListInGathering.tsx
  src/screens/mate/main/MateMainScreen.tsx
  src/utils/stackTypes.ts
Labels: refactor

#305 [refactor] 모임 생성 페이지를 모달로 변경
  src/App.tsx
  src/api/queries/gathering.ts
  src/components/gathering/CreateGatheringModal.tsx
  src/components/gathering/GatheringListRequest.tsx
  src/components/mate/ExhMateList.tsx
  src/routes/BottomRoutes.tsx
  src/screens/mate/MateMainScreen.tsx
  src/utils/stackTypes.ts
Labels: refactor

#310 [refactor] 모임에서 방문한 전시회 정보에 방문 날짜 추가
  src/assets/images/avg_rate_star.svg
  src/components/common/icon.tsx
  src/components/exhibition/ExhItemView.tsx
  src/components/mydiary/VisitedExhListFrame.tsx
  src/screens/mate/gathering/GatheringInfoScreen.tsx
  src/types/index.ts
Labels: refactor

#315 [refactor] 내 프로필 수정 폼 디자인 변경
  src/components/setting/EditArtCategory.tsx
  src/components/setting/EditNickname.tsx
  src/components/setting/EditPicture.tsx
  src/components/setting/UpdateProfile.tsx
  src/screens/login/UserInfo.tsx
  src/utils/stackTypes.ts
Labels: refactor

#316 [feature] 탈퇴 버튼 클릭 후 확인 모달 추가
  src/components/mate/NameList.tsx
  src/components/setting/modal/LeaveCheckModal.tsx
  src/screens/mate/MateMainScreen.tsx
  src/screens/mate/gathering/GatheringInfoScreen.tsx
  src/screens/setting/LeaveScreen.tsx
  src/screens/setting/SettingScreen.tsx
Labels: feature

#320 [refactor] 수정된 3가지 등록 현황 반영
  package.json
  src/components/common/exhibition/EditExhFormFrame.tsx
  src/components/regExh/RegExhDetailFormat.tsx
  src/screens/setting/regExh/CheckRegExhByUserScreen.tsx
  src/screens/setting/regExh/EditRegExhScreen.tsx
  src/screens/setting/regExh/RegExhListScreen.tsx
  src/types/index.ts
Labels: refactor

#322 Refactor/314 refactor 등록할 전시회 목록이 비어있을 경우 처리 및 새로 등록 버튼 추가
  src/api/queries/regexh.ts
  src/components/calendar/ExhListOfDayInCalendar.tsx
  src/components/common/diary/VisitedDateListForDiary.tsx
  src/components/common/exhibition/EditExhFormFrame.tsx
  src/components/exhibition/ExhDetailFormat.tsx
  src/components/exhibition/ExhSelectPeriodModal.tsx
  src/screens/calendar/CalendarScreen.tsx
  src/screens/exhibition/ExhListScreen.tsx
  src/screens/exhibition/ExhSearchByDate.tsx
  src/screens/exhibition/ExhSearchModal.tsx
  src/screens/exhibition/RegExhPreviewModal.tsx
  src/screens/exhibition/RegisterNewExhScreen.tsx
  src/screens/setting/regExh/RegExhListScreen.tsx
Labels: refactor

#323 [refactor] 푸시 알림 종류 5가지로 변경
  src/api/auth.ts
  src/api/queries/auth.ts
  src/components/common/exhibition/EditExhFormFrame.tsx
  src/components/gathering/SearchNewMateListInGathering.tsx
  src/components/setting/UpdateProfile.tsx
  src/screens/exhibition/ExhListScreen.tsx
  src/screens/login/EmailDuplicateModal.tsx
  src/screens/login/LoginScreen.tsx
  src/screens/login/UserInfo.tsx
  src/screens/setting/updateAlarm/AlarmSettingScreen.tsx
  src/screens/setting/updateAlarm/UpdateAlarm.tsx
  src/screens/setting/updateAlarm/UpdateAlarm2.tsx
  src/screens/setting/updateAlarm/UpdateAlarm3.tsx
  src/zustand/auth/auth.ts
Labels: refactor

#325 [feature] 새로 초대 받은 모임 및 모임에 추가된 전시 방문 날짜 푸시 알림 추가
  src/App.tsx
  src/api/queries/exhibition.ts
  src/components/calendar/CalendarGatheringSelector.tsx
  src/components/common/CalendarFrame.tsx
  src/components/gathering/GatheringListRequest.tsx
  src/screens/calendar/CalendarScreen.tsx
  src/screens/exhibition/ExhDetailInfoScreen.tsx
  src/screens/login/LoginScreen.tsx
  src/screens/mate/gathering/GatheringInfoScreen.tsx
  src/utils/deeplinkConfig.ts
  src/utils/pushNoti.ts
  src/utils/stackTypes.ts
Labels: feature

#329 [feature] Q&A 기능 추가
  src/App.tsx
  src/api/qna.ts
  src/api/queries/qna.ts
  src/components/common/TextInputForm.tsx
  src/components/qna/QnaEditByUserFrame.tsx
  src/components/qna/QnaOptionsModal.tsx
  src/components/regExh/RegExhDetailFormat.tsx
  src/screens/setting/SettingScreen.tsx
  src/screens/setting/qna/AnswerQnaScreen.tsx
  src/screens/setting/qna/CreateQnaScreen.tsx
  src/screens/setting/qna/QnaDetailScreen.tsx
  src/screens/setting/qna/QnaListScreen.tsx
  src/screens/setting/qna/UpdateQnaScreen.tsx
  src/types/index.ts
  src/utils/message.ts
  src/utils/stackTypes.ts
Labels: feature
