Repository Art-Diary/Frontend, pull requests merged in 2024-06, with the labels that each got.

#144 143 feature 전시회 상세정보에서 캘린더에 날짜 저장 페이지 이동
  src/App.tsx
  src/api/exhibition.ts
  src/components/visitDate/AddVisitDate.tsx
  src/screens/exhibition/ExhDetailInfo.tsx
  src/screens/exhibition/ExhToCal.tsx
  src/utils/types.ts
Labels: feature

#141 [bug] 기록 날짜 선택 스크린의 모임 종류가 안 나오는 에러 해결
  src/screens/mydiary/chooseVisitDate/ChooseVisitDateScreen.tsx
Labels: bug

#145 Refactor/142 refactor 데이터를 다시 요청하는 시점을 refetch와 react query의 invalidatequeries를 사용하여 처리
  package-lock.json
  src/api/queries/auth.ts
  src/api/queries/exhibition.ts
  src/api/queries/gathering.ts
  src/api/queries/mate.ts
  src/api/queries/mydiary.ts
  src/components/diary/modal/DeleteDiaryModal.tsx
  src/components/exhSearch/SearchExhFrame.tsx
  src/screens/calendar/CalendarScreen.tsx
  src/screens/calendar/ExhListOfDate.tsx
  src/screens/calendar/calendarDiary/CalendarDiaryList.tsx
  src/screens/exhibition/ExhDetailInfo.tsx
  src/screens/mate/MateMainScreen.tsx
  src/screens/mate/gathering/GatheringDiaryListScreen.tsx
  src/screens/mate/gathering/GatheringInfoScreen.tsx
  src/screens/mate/gathering/addVisitExhibition/SearchAddVisitExhInGatheringScreen.tsx
  src/screens/mate/mateDiary/MateDiaryListScreen.tsx
  src/screens/mate/mateExhList/MateExhList.tsx
  src/screens/mydiary/MyExhList.tsx
  src/screens/mydiary/MyExhSearchScreen.tsx
  src/screens/mydiary/SearchExhList.tsx
  src/screens/mydiary/chooseVisitDate/ChooseVisitDateScreen.tsx
  src/screens/mydiary/mydiaryList/MyDiaryListScreen.tsx
  src/screens/setting/favoriteList/FavoriteListScreen.tsx
Labels: refactor

#147 Bug/146 bug 모임 메인 화면과 관련된 화면 중 오류가 발생할 때 헤더가 없어지는 화면들 수정
  src/components/common/ErrorMessageView.tsx
  src/components/mate/NameList.tsx
  src/routes/BottomRoutes.tsx
  src/routes/mate/MateDiaryRoutes.tsx
  src/screens/mate/gathering/GatheringInfoScreen.tsx
  src/screens/mate/main/AddNewMateScreen.tsx
  src/screens/mate/main/CreateGatheringScreen.tsx
  src/screens/mate/main/ExhMateList.tsx
  src/screens/mate/main/GatheringListRequest.tsx
  src/screens/mate/main/MateMainScreen.tsx
  src/screens/mate/main/SearchNewMateList.tsx
  src/screens/mate/mate/mateDiary/MateDiaryBackScreen.tsx
  src/screens/mate/mate/mateDiary/MateDiaryListScreen.tsx
  src/screens/mate/mate/mateExhList/MateExhList.tsx
  src/screens/mate/mate/mateExhList/MateExhListScreen.tsx
Labels: bug, refactor

#151 [bug] 설정 관련 화면 중 오류가 발생할 때 헤더가 없어지는 화면들 수정
  src/App.tsx
  src/api/queries/auth.ts
  src/components/setting/UpdateProfile.tsx
  src/routes/setting/FavoriteRoutes.tsx
  src/routes/setting/SettingRoutes.tsx
  src/screens/setting/SettingScreen.tsx
  src/screens/setting/favoriteList/EditFavoriteScreen.tsx
  src/screens/setting/favoriteList/FavoriteListScreen.tsx
  src/screens/setting/favoriteList/FetchFavoriteList.tsx
  src/screens/setting/nameTag/ProfileNameTag.tsx
  src/screens/setting/updateProfile/EditNickname.tsx
  src/screens/setting/updateProfile/EditProfileScreen.tsx
  src/utils/types.ts
Labels: bug

#157 [bug] 내 기록 탭 관련 화면 중 오류가 발생할 때 헤더가 없어지는 화면들 수정
  src/components/exhSearch/SearchExhResult.tsx
  src/screens/mate/gathering/addVisitExhibition/SearchAddVisitExhInGatheringScreen.tsx
  src/screens/mydiary/MyExhList.tsx
  src/screens/mydiary/MyExhSearchScreen.tsx
  src/screens/mydiary/chooseVisitDate/ChooseVisitDateScreen.tsx
  src/screens/mydiary/chooseVisitDate/FetchMyStoredDateListOfExh.tsx
  src/screens/mydiary/mydiaryList/MyDiaryList.tsx
  src/screens/mydiary/mydiaryList/MyDiaryListScreen.tsx
Labels: bug

#158 [bug] 캘린더 탭 관련 화면 중 오류가 발생할 때 헤더가 없어지는 화면들 수정
  src/screens/calendar/CalendarScreen.tsx
  src/screens/calendar/ExhListOfDayInCalendar.tsx
  src/screens/calendar/GatheringSelector.tsx
  src/screens/calendar/calendarDiary/CalendarDiaryList.tsx
Labels: bug, refactor

#160 [bug] 개인 방문 다이어리 수정 시 날짜 변경 페이지에서 selector 값이 개인으로 고정되도록 수정
  src/screens/mydiary/chooseVisitDate/ChooseVisitDateScreen.tsx
Labels: bug

#163 [feature] 공유하기 구현
  .gitignore
  android/app/build.gradle
  env.d.ts
  package.json
  src/routes/BottomRoutes.tsx
  src/screens/exhibition/ExhDetailInfo.tsx
  src/screens/exhibition/ExhShare.tsx
  src/screens/exhibition/Link.ts
Labels: feature

#166 [feature] 카카오 로그인 구현 완료
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/values/strings.xml
  android/build.gradle
  package.json
  src/api/queries/auth.ts
  src/components/setting/UpdateProfile.tsx
  src/screens/login/KakaoLogin.ts
  src/screens/login/LoginScreen.tsx
  src/screens/login/UserInfo.tsx
  src/screens/setting/SettingScreen.tsx
  src/screens/setting/updateProfile/EditProfileScreen.tsx
  src/zustand/auth/auth.ts
Labels: feature

#169 [feature] 알림 서비스 구현
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  index.ts
  package.json
  src/App.tsx
  src/api/auth.ts
  src/api/queries/auth.ts
  src/screens/exhibition/ExhDetailInfo.tsx
  src/screens/login/GoogleLogin.ts
  src/screens/login/LoginScreen.tsx
  src/screens/setting/SettingScreen.tsx
  src/screens/setting/updateAlarm/AlarmSettingScreen.tsx
  src/utils/deeplinkConfig.ts
  src/utils/pushNoti.ts
Labels: feature

#171 170 [feature] 기록 더보기 페이지
  package.json
  src/App.tsx
  src/screens/exhibition/ExhDetailInfo.tsx
  src/screens/exhibition/ExhToMoreReview.tsx
  src/utils/types.ts
Labels: feature

#172 Feature/168 feature 기록 작성 에디터 구현
  package.json
  src/assets/fonts/stylesheet.ts
  src/assets/images/align_icon.svg
  src/assets/images/color_change_icon.svg
  src/assets/images/index.ts
  src/components/diary/ContentsInfo.tsx
  src/components/diary/DiaryBackFrame.tsx
  src/screens/mydiary/writeDiary/CustomDiaryEditor.tsx
  src/screens/mydiary/writeDiary/GetPhoto.ts
  src/screens/mydiary/writeDiary/WriteMyDiaryContentsScreen.tsx
Labels: feature
