Repository Art-Diary/Frontend, pull requests merged in 2024-09, with the labels that each got.

#257 [256 feature] 등록 전시 수정삭제 버튼 추가
  src/assets/images/edit_reg_exh.svg
  src/assets/images/index.ts
  src/assets/images/trash_reg_exh.svg
  src/components/common/icon.tsx
  src/components/setting/RegExhOptionsModal.tsx
  src/screens/setting/CheckRegExh.tsx
Labels: feature

#259 [bug] 관리자인지 확인 후 관리자용 전시회 등록 페이지 표시 추가
  src/components/setting/UpdateProfile.tsx
  src/screens/login/EmailDuplicateModal.tsx
  src/screens/login/LoginScreen.tsx
  src/screens/login/UserInfo.tsx
  src/screens/setting/RegisterNewExhScreen.tsx
  src/screens/setting/SettingScreen.tsx
  src/zustand/auth/auth.ts
Labels: bug

#261 Feature/260 feature 관리자의 등록된 전시회 수정 구현
  src/api/queries/regexh.ts
  src/components/regexh/ExhDetailFormat.tsx
  src/screens/exhibition/ExhAddFormScreen.tsx
  src/screens/setting/CheckRegExh.tsx
  src/screens/setting/ConfirmRegExh.tsx
  src/screens/setting/ConfirmRegExhScreen.tsx
  src/screens/setting/RegisterNewExhScreen.tsx
  src/screens/setting/ShowConfirmedRegExh.tsx
  src/utils/stackTypes.ts
Labels: feature

#267 [refactor] 관리자용 등록 전시회 삭제 아이콘 없애고, 전시회 목록의 마지막 아이템에 아래 공간 추가
  src/components/exhibition/ExhItemView.tsx
  src/screens/exhibition/ExhAddButton.tsx
  src/screens/setting/ShowConfirmedRegExh.tsx
Labels: refactor
