Repository Art-Diary/Frontend, pull requests merged in 2024-05, with the labels that each got.

#100 Feature/98 feature 전시메이트 탭 화면의 전시메이트 목록 조회 구현
  src/api/mate.ts
  src/api/queries/mate.ts
  src/components/mate/NameList.tsx
  src/screens/mate/ExhMateList.tsx
  src/screens/mate/GatheringList.tsx
  src/screens/mate/MateListScreen.tsx
  src/screens/mate/NameTag.tsx
Labels: feature, refactor

#90 선택된 옵션 보여주기및 삭제 기능
  src/api/exhibition.ts
  src/api/queries/exhibition.ts
  src/components/exhibition/OptionsModal.tsx
  src/screens/exhibition/ExhListScreen.tsx
  src/screens/exhibition/ExhSearchByDate.tsx
  src/screens/exhibition/ExhSearchModal.tsx
  src/screens/exhibition/ExhSearchName.tsx
  src/zustand/exhibition/exhibition.ts
Labels: feature

#103 [feature] 모임 상세 정보 화면 구현
  src/App.tsx
  src/api/gathering.ts
  src/api/queries/gathering.ts
  src/components/diary/StoredExhList.tsx
  src/components/exhibition/ExhItemView.tsx
  src/screens/mate/GatheringInfoScreen.tsx
Labels: feature

#107 [feature] 로그인 첫 화면 디자인
  src/App.tsx
  src/components/common/GreyNameTag.tsx
  src/routes/BottomRoutes.tsx
  src/screens/exhibition/ExhListScreen.tsx
  src/screens/login/LoginScreen.tsx
  src/screens/setting/SettingScreen.tsx
Labels: feature

#108 [feature] 추가할 모임 이름 작성 화면 구현
  src/App.tsx
  src/api/gathering.ts
  src/api/queries/gathering.ts
  src/components/diary/DiaryList.tsx
  src/components/mate/NameList.tsx
  src/screens/mate/CreateGatheringScreen.tsx
  src/screens/mate/MateListScreen.tsx
Labels: feature

#109 Feature/105 feature 구글 로그인 구현
  .gitignore
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  babel.config.js
  env.d.ts
  package.json
  src/api/auth.ts
  src/api/client.ts
  src/api/queries/auth.ts
  src/screens/login/LoginScreen.tsx
  tsconfig.json
Labels: feature

#113 106 refactor 같은 카테고리 내 여러 옵션 사용 가능
  src/App.tsx
  src/api/exhibition.ts
  src/api/queries/exhibition.ts
  src/screens/exhibition/ExhListScreen.tsx
  src/screens/exhibition/ExhSearchByDate.tsx
  src/screens/exhibition/ExhSearchModal.tsx
Labels: refactor

#112 [feature] 전시 메이트 추가 화면 구현 완료
  src/App.tsx
  src/api/mate.ts
  src/api/queries/mate.ts
  src/components/exhSearch/SearchExhFrame.tsx
  src/screens/mate/AddNewMateScreen.tsx
  src/screens/mate/ExhMateList.tsx
  src/screens/mate/MateListScreen.tsx
  src/screens/mate/NameTag.tsx
  src/screens/mate/SearchNewMateList.tsx
  src/screens/setting/nameTag/ProfileNameTag.tsx
Labels: feature

#116 [refactor]가격 카테고리 값 하나만 선택
  src/screens/exhibition/ExhSearchModal.tsx
Labels: refactor

#117 Feature/111 feature 전시 메이트의 공개된 기록이 있는 전시회 목록 화면 구현
  src/App.tsx
  src/api/mate.ts
  src/api/queries/mate.ts
  src/components/diary/VisitedExhListFrame.tsx
  src/routes/mate/MateDiaryRoutes.tsx
  src/screens/mate/ExhMateList.tsx
  src/screens/mate/mateExhList/MateExhList.tsx
  src/screens/mate/mateExhList/MateExhListScreen.tsx
  src/screens/mydiary/MyExhList.tsx
  src/screens/mydiary/SearchExhList.tsx
  src/zustand/mate/mate.ts
Labels: feature

#125 [refactor] 검색 키워드 빈 문자열 검사 공통 함수 분리 & 사용자 정보 수정 공통 컴포넌트 분리
  src/components/setting/UpdateProfile.tsx
  src/screens/exhibition/ExhSearchName.tsx
  src/screens/login/InitProfileScreen.tsx
  src/screens/login/LoginScreen.tsx
  src/screens/mate/AddNewMateScreen.tsx
  src/screens/mydiary/MyExhSearchScreen.tsx
  src/screens/mydiary/writeDiary/WriteMyDiaryContentsScreen.tsx
  src/screens/mydiary/writeDiary/WriteMyDiaryInfoScreen.tsx
  src/screens/setting/LeaveScreen.tsx
  src/screens/setting/updateProfile/EditNickname.tsx
  src/screens/setting/updateProfile/EditProfileScreen.tsx
  src/utils/CheckKeyword.ts
Labels: refactor

#127 [refactor] 로그인하는 사용자에 따라 api 요청의 헤더에 들어가는 userId가 달라질 수 있도록 구현
  package.json
  src/App.tsx
  src/api/client.ts
  src/api/queries/auth.ts
  src/components/common/ErrorMessageView.tsx
  src/components/common/GreyNameTag.tsx
  src/components/setting/UpdateProfile.tsx
  src/screens/login/LoginScreen.tsx
  src/screens/login/UserInfo.tsx
  src/screens/setting/LeaveScreen.tsx
  src/screens/setting/SettingScreen.tsx
  src/screens/setting/nameTag/ProfileNameTag.tsx
  src/screens/setting/updateAlarm/UpdateAlarm1.tsx
  src/screens/setting/updateAlarm/UpdateAlarm2.tsx
  src/screens/setting/updateAlarm/UpdateAlarm3.tsx
  src/screens/setting/updateProfile/EditNickname.tsx
  src/screens/setting/updateProfile/EditProfileScreen.tsx
  src/zustand/auth/auth.ts
Labels: refactor

#130 [feature] 모임 나가기 api 추가 구현 완료
  src/api/gathering.ts
  src/api/queries/gathering.ts
  src/screens/mate/gathering/GatheringDiaryListScreen.tsx
  src/screens/mate/gathering/GatheringInfoScreen.tsx
Labels: feature

#133 Refactor/131 refactor 검색 결과가 없는 경우 및 모달 외부 영역 터치 시 모달 닫기 처리 캘린더에서 특정 날짜에 전시회 추가 이동 구현
  src/components/common/modal/ConfirmationModal.tsx
  src/screens/calendar/ExhListOfDate.tsx
  src/screens/exhibition/ExhListScreen.tsx
  src/screens/mate/SearchNewMateList.tsx
  src/screens/mydiary/SearchExhList.tsx
  src/zustand/calendar/addSchedule.ts
Labels: bug, feature, refactor

#135 [feature] 모임에서 방문한 전시회에 기록 추가
  src/api/queries/mydiary.ts
  src/components/diary/UpdateDelete.tsx
  src/screens/mate/gathering/GatheringDiaryListScreen.tsx
  src/screens/mydiary/SearchExhList.tsx
  src/screens/mydiary/chooseVisitDate/ChooseVisitDateList.tsx
  src/screens/mydiary/chooseVisitDate/ChooseVisitDateScreen.tsx
  src/screens/mydiary/mydiaryList/MyDiaryListScreen.tsx
  src/zustand/mydiary/writeMyDiary.ts
Labels: feature
